version: "3.8"
services:
  api:
    build: .
    image: takarasuccess/lamp
    privileged: true
    container_name: lamp
    hostname: lamp
    volumes:
      - "mysql57:/var/lib/mysql"

# docker volume create mysql57
volumes:
  mysql57:
    external: true
