version: "3.8"
services:
  api:
    build: .
    image: takarasuccess/lamp
    privileged: true
    container_name: lamp
    hostname: lamp
    volumes:
      - "mysql56:/var/lib/mysql"

# docker volume create mysql56
volumes:
  mysql56:
    external: true
