version: "3.8"
services:
  api:
    build: .
    image: lamp
    privileged: true
    container_name: lamp
    hostname: lamp
    volumes:
      - "mysql:/var/lib/mysql"

# docker volume create mysql
volumes:
  mysql:
    external: true
